/**
 * Sulfur backend
 * El login exitoso de AuthService devuelve un Usuario con un campo \"token\". Dicho token se debe incluir como header de las llamadas del resto de las operaciones de cada servicio.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';
import { Material } from './Material';

export class MaterialImp implements Material {
    id?: number;

    nombre: string;

    descripcion?: string;

    tipoMaterial?: models.TipoMaterial;

    public constructor(m: Material) {
        this.id = m.id;
        this.nombre = m.nombre;
        this.descripcion = m.descripcion;
        this.tipoMaterial = m.tipoMaterial;
    }
}
