/**
 * Sulfur backend
 * El login exitoso de AuthService devuelve un Usuario con un campo \"token\". Dicho token se debe incluir como header de las llamadas del resto de las operaciones de cada servicio.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';
import { Material } from './Material';
import {TipoEquipo} from "./TipoEquipo";

export class TipoEquipoImp implements TipoEquipo {
    idTipoEquipo?: number;

    dibujo: string;

    descripcion: string;


    public constructor(t: TipoEquipo) {
        this.idTipoEquipo = t.idTipoEquipo;
        this.dibujo = t.dibujo;
        this.descripcion = t.descripcion;
    }
}
